### ISSUE TITLE
open_agb_firm will not boot

### ISSUE THREAD

**Issue by BrittanyOfKoppai** [profi200/open_agb_firm#15] opened 2020-09-09 21:54 UTC
I'm using an old 3ds, I tried both the intro version and no intro version. When booted, the 3ds simply boots to a black screen, both top and bottom. When any buttons are pressed, the system shuts down.

**Comment by fox8091** [comment] 2020-09-10 06:20
Duplicate of #10 and #14.

**Comment by profi200** [comment] 2020-09-20 19:58
Please continue in issue #10. Closing this.

**Closed by profi200** 2020-09-20 19:58 UTC
