### ISSUE TITLE
Audio cord problem

### ISSUE THREAD

**Issue by PiptonyZX** [profi200/open_agb_firm#84] opened 2022-09-22 23:42 UTC
3ds menu music work fine.  Reboot then press start to load it up.  Load rom.   Audio in cord for speaker is cut off.  Only audio come through 3ds speaker.  Kept trying unplug and plug, nothing happen.

Sorry if my grammar is not good.

**Comment by profi200** [comment] 2022-09-23 22:56
If you are using a headset try holding one of the buttons on it for a few seconds.

Duplicate of #11.

**Closed by profi200** 2022-09-23 22:56 UTC

**Comment by PiptonyZX** [comment] 2022-09-24 00:32
I dont use headset.  I use normal audio cord like male to male.
