### ISSUE TITLE
Issues booting open_agb_firm twice in a row

### ISSUE THREAD

**Issue by twocows** [profi200/open_agb_firm#18] opened 2020-09-22 15:22 UTC
If I boot open_agb_firm and run a game, then power off, then try to boot into open_agb_firm again, it just hangs. If I then boot into the normal system software, let it come up, power down, then boot into open_agb_firm again, it works fine (but the problem will still come back if I try to do it twice). I didn't have this problem before updating to build 2020-09-08.

I'm using an O3DS XL, Luma should be on the latest version. This is using the version of open_agb_firm that has the GBA bios splash.

**Comment by shar33f** [comment] 2020-09-22 15:25
It's a known bug, see https://github.com/profi200/open_agb_firm/issues/17 and https://github.com/profi200/open_agb_firm/issues/10

Hopefully will be fixed soon in a future release.

**Comment by profi200** [comment] 2020-09-22 15:41
Duplicate of #10.

**Closed by profi200** 2020-09-22 15:41 UTC
