### ISSUE TITLE
First launch works, next launch crashes (hangs)

### ISSUE THREAD

**Issue by shar33f** [profi200/open_agb_firm#17] opened 2020-09-20 16:50 UTC
I'm running open_agb_firm alpha build 2020-09-08 on a new 3ds (non-xl) and the first time I launch it, it works perfectly; I see the file browser on the lower screen and can load all roms no problem (it runs really nicely!!). When I'm done playing, I press the power button to turn off my 3ds and then press power again (while holding start) and both screens just stay black and the blue power LED stays on solid. I have to pull the battery to get around the crash / hang. Then when I power on again the next time while holding start everything works fine again. Of course I have to reset my system date and time every time I pull the battery, otherwise everything works fine but would be nice if it worked properly every time. Is anyone else experiencing the same issue?

EDIT: I noticed I can avoid the crash / hang if I boot into regular 3ds mode after loading open_agb_firm and powering off. In other words I cannot load open_agb_firm twice consecutively without crashing my system, but I can run it multiple times by booting into regular 3ds mode after every run of open_ags_firm.

**Comment by profi200** [comment] 2020-09-20 19:26
Does it power off if you press A while on the blackscreens? If so this is the known screen init incompatibility between release fastboot3DS/Luma/GodMode9.

**Comment by shar33f** [comment] 2020-09-20 19:40
Yes that works, thank you! So much better then pulling the battery and then having to reset the date and time :) I'll use this workaround and wait patiently then until this is addressed in a future release. Until then thanks so much for this amazing software!!

**Comment by profi200** [comment] 2020-09-20 19:59
Duplicate of issue #10.

**Closed by profi200** 2020-09-20 19:59 UTC
