### ISSUE TITLE
[Request] Add button mapping for L-Y & R-X

### ISSUE THREAD

**Issue by jjkkyu** [profi200/open_agb_firm#71] opened 2022-06-05 14:17 UTC
Hi, would you add button mapping for L-Y & R-X?
It means when press Y button, is will also reflect L button action, and the same for X button to reflect R.
This would help when playing some fighting games.

**Comment by profi200** [comment] 2022-06-05 15:23
Duplicate of #25. I don't know when i will add it. It needs some bigger changes.

**Closed by profi200** 2022-06-05 15:23 UTC
