### ISSUE TITLE
Headphones don't work

### ISSUE THREAD

**Issue by BrittanyOfKoppai** [profi200/open_agb_firm#11] opened 2020-08-11 02:01 UTC
When booting open_agb_firm (I used the no intro version) despite my headphones being plugged in, the audio still streamed through the system's built in speakers. Using an old 3ds if that matters.

**Comment by profi200** [comment] 2020-08-12 20:59
I don't know why the automatic output switching is broken for a select few people but i know how Nintendo handles this and gets around the issue.
That said it's not high priority but i will look into it eventually.

**Comment by PepeShake** [comment] 2020-08-13 22:04
I get this problem sometimes. Unplugging the headphones and plugging them back in seems to fix it.

**Comment by wiceli** [comment] 2021-02-16 19:33
I have the same problem, the sound doesn't come out from the earbuds! the latest release is used.

**Comment by profi200** [comment] 2021-02-17 14:43
As mentioned above i don't know why the auto detection is broken but it can be manually handled by the CPU.

**Comment by sak-pase** [comment] 2021-09-27 00:42
I only have this problem with Apple headphones, and I can usually get them to work by holding the Play/Pause button on them for about a second after re-plugging them in. Probably has something to do with Apple's disdain for industry standards.

**Comment by profi200** [comment] 2021-09-27 11:02
Not sure about that. I still don't know why the output switching is so wonky. Going by a similar datasheet it measures output pins and switches if it detects changes. In theory it's fine. No idea why it's broken in practice. I still have not implemented the second detection method Nintendo uses.

**Comment by OrangeFlavored** [comment] 2021-11-07 02:19
Seems like it's dependent on the cable used or something, using M-M extension cord into portable amp which my headphones are connected to was not detected, but plugging the same headphones directly into the 3DS worked fine.

**Comment by profi200** [comment] 2021-11-07 10:39
Forgot who posted it originally but it seems the issue is exclusive to 4 pin headphones/headsets. You can usually make them work by holding a button for 1-2 seconds (tested it). If there is no button that won't work of course.

**Comment by PiptonyZX** [comment] 2022-09-27 14:09
Used 3 pins for short range cord and it work and no button at all.   It work fine.  I tested long range, didnt work.   Only work under 3ft cord.

**Comment by PiptonyZX** [comment] 2022-09-27 14:47
Forgot to mention, only one speaker does work.   Model name is 19YX01.  Brand name, well it kinda weird name and it is pretty long.  Some kind of language I think.

SHENZHEN JIA HUA LI DIAN ZI YOU XIAN GONG SI.

If you want use other speaker, then you must leave cord on your 3ds.  If you take it off on 3ds, then it wont work wne you plug it up.   You have to start over from gm3 menu.  (Not main menu where you dump it) I test it with other speaker to plug and it work as long you jeep cord on your 3ds.   If you leave cord on speaker and 3ds after turn it off, then you wont have to use this model of speaker again as long you dont take iff from 3ds.  If you do, then you have to use this model of speaker.

**Comment by profi200** [comment] 2022-09-27 15:56
Might have mentioned it above already but it's not clear to me how CODEC does the detection. Might be measuring impedance or similar. And as mentioned Nintendo uses a different method of detection that uses a physical switch inside the headphone jack. I will implement Nintendos way of detection to fix these issues eventually.

**Comment by PiptonyZX** [comment] 2022-09-27 17:43
Here is video to proof.

Oh okay.   Hope work it out with Nintendo.

https://youtu.be/3IQiNLMxsu4

**Comment by profi200** [comment] 2023-08-05 00:13
This is now fixed. See nightlies/actions tab.

**Closed by profi200** 2023-08-05 00:13 UTC
Labels: bug
